# -- coding: utf-8 --

# Form implementation generated from reading ui file 'VMR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Interface")
        MainWindow.resize(1350, 2882)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 441, 891))
        self.label.setStyleSheet("background:url(E:/Final -Gesture-Controlled-Virtual-Mouse-main/src/web.png)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/Final -Gesture-Controlled-Virtual-Mouse-main/src/web.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 0, 421, 891))
        self.label_2.setStyleSheet("background:url(E:/Final-Gesture-Controlled-Virtual-Mouse-main/src/eye.jpeg)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:/Final -Gesture-Controlled-Virtual-Mouse-main/src/eye.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(890, 0, 411, 891))
        self.label_3.setStyleSheet("background:url(E:/Final -Gesture-Controlled-Virtual-Mouse-main/src/voice.jpeg)")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:/Final -Gesture-Controlled-Virtual-Mouse-main/src/voice.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.Hand = QtWidgets.QPushButton(self.centralwidget)
        self.Hand.setGeometry(QtCore.QRect(140, 210, 141, 81))
        self.Hand.setStyleSheet("background:rgb(49, 49, 49);\n""font: 20pt \"Calibri\";")
        self.Hand.setDefault(True)
        self.Hand.setFlat(True)
        self.Hand.setObjectName("Hand")
        self.Eye = QtWidgets.QPushButton(self.centralwidget)
        self.Eye.setGeometry(QtCore.QRect(620, 200, 141, 81))
        self.Eye.setStyleSheet("font: 20pt \"Calibri\";\n""background:rgb(49, 49, 49);")
        self.Eye.setAutoDefault(False)
        self.Eye.setDefault(True)
        self.Eye.setFlat(True)
        self.Eye.setObjectName("Eye")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1110, 200, 141, 81))
        self.pushButton_3.setStyleSheet("background:rgb(49, 49, 49);\n""font: 20pt \"Calibri\";")
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Hand.clicked.connect(self.run_hand)
        self.Eye.clicked.connect(self.run_eye)
        self.pushButton_3.clicked.connect(self.run_Voice)


    def run_hand(self):
        os.system("Python Gesture_Controller.py")
    def run_eye(self):
        os.system("Python iris.py")
    def run_Voice(self):
        os.system("python proton.py")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Hand.setText(_translate("MainWindow", "Hand"))
        self.Eye.setText(_translate("MainWindow", "Eye"))
        self.pushButton_3.setText(_translate("MainWindow", "Voice"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())